credentials:
  usernames:
    admin:
      email: admin@example.com
      failed_login_attempts: 0
      logged_in: False
      name: Admin User
      password: abc123
    user:
      email: user@example.com
      failed_login_attempts: 0
      logged_in: False
      name: Regular User
      password: def456
cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
pre-authorized:
  emails: []
